<%
if ENV['DB_POOL']
  web_pool_size = ENV['DB_POOL'].to_i
elsif ENV['MAX_THREADS']
  web_pool_size = ENV['MAX_THREADS'].to_i # + 1 if buffer needed
else
  web_pool_size = 5
end
%>
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>
  connect_timeout:  # DELIBERATELY LEFT BLANK FOR QUOTAGUARD STATIC (PRODUCTION)
  checkout_timeout: #DELIBERATELY LEFT BLANK FOR QUOTAGUARD STATIC (PRODUCTION)

development:
  <<: *default
  database: bell_bird_dev

test:
  <<: *default
  database: bell_bird

production:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= web_pool_size %>

production_sidekiq:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= (ENV['SIDEKIQ_CONCURRENCY'] || 25).to_i + 2 %>
  # Intentionally don't set timeout on sidekiq
